development:
  adapter: postgresql
  encoding: unicode
  database: financ_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost


test: &TEST
  adapter: postgresql
  encoding: unicode
  database: financ_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: financ_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

cucumber:
  <<: *TEST

